site_name: ForFansubs Wiki
site_url: https://forfansubs.github.io/docs/
repo_url: https://github.com/ForFansubs
site_description: "ForFansubs paketlerinin nasıl kullanılacağını öğreten wiki"
nav:
  - Ana sayfa: 'index.md'
  - 'Kurulum & Çalıştırma':
    - Gereken Programlar: 'gereken-programlar.md'
    - Yükleme Talimatları: 'yukleme-talimatlari.md'
    - Yayına Hazırlanma: 'yayina-hazirlanma.md'
    - Pre-render (SEO): 'prerender.md' 
  - 'Kurulumdan Sonra': 
    - Güncelleme Geldiğinde: 'guncelleme-geldiginde.md'
    - Environment Variables (.env): 'environment-variables.md'
    - Admin Hesabı Açma: 'admin-kullanicisi.md'
google_analytics:
  - 'UA-82378950-4'
  - 'auto'
extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://fgl.moe/'
    - icon: fontawesome/brands/github
      link: 'https://github.com/ayberktandogan'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/ayberk-tandogan/'
theme:
  language: 'tr'
  font:
    text: 'Source Sans Pro'
    code: 'Source Code Pro'
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/favicon.ico'
  feature:
    instant: true
    tabs: false
  name: material
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.tabbed
  - codehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
extra_javascript:
  - 'assets/js/extra.js'
extra_css:
  - 'assets/css/extra.css'
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - tr
  - git-revision-date-localized
  - minify:
      minify_html: true
copyright: <a href="https://ayberktandogan.github.io" target="_blank" rel="noopener noreferrer">ayberktandogan © 2020</a>